language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

install:
  - composer install --prefer-dist

script:
  - composer run cs-check
  - composer run coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
